name: drupal-vue-graphql

proxy:
  node:
    - "drupal-vue-graphql.lndo.site:3000"

tooling:
  npm:
    service: node
    description: Run NPM commands within the node service.

  dev:
    service: node
    description: Run the development server.
    cmd: npm run dev

  genql:
    service: node
    description: Generate GraphQL queries and mutations.
    cmd: npm run genql

services:
  node:
    type: node:18
    ssl: true
    sslExpose: false
    port: 3000
    scanner: false
    build:
      - npm ci
    overrides:
      ports:
        - 3000
        - 8002
      environment:
        NODE_ENV: development
        PORT: 3000
        NODE_TLS_REJECT_UNAUTHORIZED: 0
        VUE_APP_GRAPHQL_ENDPOINT: "https://drupal-boilerplate.lndo.site/graphql"
