name: drupal-vue-graphql

env_file:
  - .env

services:
  node:
    type: node:18
    scanner: false
    ports:
      - 3010:3010
    globals:
      '@genql/cli': latest
    build:
      - npm ci

tooling:
  npm:
    service: node
    description: Run NPM commands within the node service.

  dev:
    service: node
    cmd: npm run dev -- --port 3010 --host

  build:
    service: node
    cmd: npm run build

  genql:
    service: node
    cmd: genql --sort --esm --endpoint "$VITE_DRUPAL_BASE_URL/$VITE_GRAPHQL_PATH" --output ./src/services/drupal/generated
    shell: bash
    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

