name: drupal-vue-graphql

env_file:
  - .env

tooling:
  npm:
    service: node
    description: Run NPM commands within the node service.

  dev:
    service: node
    cmd: npm run dev

  build:
    service: node
    cmd: npm run build

  genql:
    service: node
    cmd: genql --sort --endpoint "$VITE_GRAPHQL_ENDPOINT" --output ./src/drupal/gen

services:
  node:
    type: node:18
    scanner: false
    ports:
      - 3009:3009
    build:
      - npm ci
    overrides:
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0